version: "3.9"

services:
  plantuml:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: openzeppelin-puml
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    