version: '3.9'
services:
  plantuml:
    volumes:
      - .:/workspace:cached
      - vscode-exts:/root/.vscode-server/extensions
      - vscode-exts-insiders:/root/.vcode-server-insiders/extensions
    command: /bin/sh -c "while sleep 1000; do :; done"

volumes:
  vscode-exts:
  vscode-exts-insiders:
