@startuml OpenZeppelin Contracts Upgradeable Access Control contract diagram
title OpenZeppelin Contracts Upgradeable Access Control contract diagram

!includesub ownership-transferred.event.puml!OwnershipTransferredEvent

!startsub AccessControlUpgradeableContract
package openzeppelin {
  package contracts-upgradeable {
    package access {
      class AccessControlUpgradeable<<contract>> {
        -@initializer()
        -@onlyOwner()
        #constructor()
        +owner()
        +renounceOwnership()
        +transferOwnership(newOwner)
        *initializer() <<initializer>>
      }

      AccessControlUpgradeable -> OwnershipTransferred : emits
    }
  }
}
!endsub

@enduml